name: CI
on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
  Script_execution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r General_Scripts/requirements.txt

    - name: Execute StuPo crawler
      run: python Knowledge/Pruefungsamt_Thesis/Stupo_Skript/crawler.py

    - name: Find all combine_ directories and combine pdf files
      run: |
        dirs=$(find . -path "./combine_*" -type d)
        for d in $dirs; do python Scripts/combine_pdfs.py "../$d"; done

    - name: Copy all relevant files into one directory
      run: |
        mkdir chatbot_knowledge
        files=$(find . -path "./Knowledge/*" -type f  | \
          sed 's/^.*temp.*$//' | \
          sed 's/^.*\.py$//' | \
          sed 's/^.*survey.*$//' | \
          sed 's/^.*combine_.*$//' | \
          sed 's/^.*requirements.txt$//')
        for f in $files; do cp $f chatbot_knowledge/; done

    - name: Upload all files Knowledge files
      uses: actions/upload-artifact@v4
      with:
        name: chatbot_knowledge
        overwrite: true
        path: chatbot_knowledge/*