name: CI
on:
  push:
    branches: ['*']
    paths-ignore:
      - '*/temp*'
      - '*.temp*'
      - '*.py'
  workflow_dispatch:

jobs:
  StuPo_crawler:
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip install -r Knowledge/StuPo_Crawler/requirements.txt

    - name: Execute StuPo crawler
      run: python Knowledge/StuPo_Crawler/crawler.py

  Gather_files:
    - name: Upload all files (excluding temp_ directories and files)
      uses: actions/upload-artifact@v4
      with:
        path: |
          Knowledge/**/*
          !**/temp*/**
          !**/temp*